"""Add enhanced job and target role fields

Revision ID: a975969fa712
Revises: 
Create Date: 2025-04-22 10:35:57.378273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a975969fa712'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_events')
    op.drop_table('email_correspondence')
    op.add_column('job_cache', sa.Column('location', sa.String(), nullable=True))
    op.add_column('job_cache', sa.Column('post_date', sa.String(), nullable=True))
    op.add_column('job_cache', sa.Column('total_years_experience', sa.Integer(), nullable=True))
    op.add_column('job_cache', sa.Column('candidate_gaps', sa.Text(), nullable=True))
    op.add_column('job_cache', sa.Column('location_type', sa.String(), nullable=True))
    op.add_column('job_cache', sa.Column('company_size', sa.String(), nullable=True))
    op.add_column('job_cache', sa.Column('company_stability', sa.String(), nullable=True))
    op.add_column('job_cache', sa.Column('glassdoor_rating', sa.String(), nullable=True))
    op.add_column('job_cache', sa.Column('employee_count', sa.String(), nullable=True))
    op.add_column('job_cache', sa.Column('year_founded', sa.String(), nullable=True))
    op.add_column('job_cache', sa.Column('growth_stage', sa.String(), nullable=True))
    op.add_column('job_cache', sa.Column('market_position', sa.String(), nullable=True))
    op.add_column('job_cache', sa.Column('development_opportunities', sa.Text(), nullable=True))
    op.add_column('target_roles', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('target_roles', sa.Column('next_steps', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target_roles', 'next_steps')
    op.drop_column('target_roles', 'requirements')
    op.drop_column('job_cache', 'development_opportunities')
    op.drop_column('job_cache', 'market_position')
    op.drop_column('job_cache', 'growth_stage')
    op.drop_column('job_cache', 'year_founded')
    op.drop_column('job_cache', 'employee_count')
    op.drop_column('job_cache', 'glassdoor_rating')
    op.drop_column('job_cache', 'company_stability')
    op.drop_column('job_cache', 'company_size')
    op.drop_column('job_cache', 'location_type')
    op.drop_column('job_cache', 'candidate_gaps')
    op.drop_column('job_cache', 'total_years_experience')
    op.drop_column('job_cache', 'post_date')
    op.drop_column('job_cache', 'location')
    op.create_table('email_correspondence',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=True),
    sa.Column('direction', sa.VARCHAR(), nullable=True),
    sa.Column('sender', sa.VARCHAR(), nullable=True),
    sa.Column('recipients', sa.VARCHAR(), nullable=True),
    sa.Column('subject', sa.VARCHAR(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('received_date', sa.VARCHAR(), nullable=True),
    sa.Column('sent_date', sa.VARCHAR(), nullable=True),
    sa.Column('thread_id', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('has_calendar_invite', sa.VARCHAR(), nullable=True),
    sa.Column('processed_calendar', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_cache.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_application_id', sa.INTEGER(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.VARCHAR(), nullable=True),
    sa.Column('end_time', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('calendar_event_id', sa.VARCHAR(), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
