version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ../config:/app/config
      # Only mount credentials if GOOGLE_APPLICATION_CREDENTIALS is set
      - ${GOOGLE_APPLICATION_CREDENTIALS:-./.dummy-credentials.json}:/app/credentials/credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-/app/credentials/credentials.json}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - SLACK_API_TOKEN=${SLACK_API_TOKEN:-}
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID:-}
      - MEDIUM_API_KEY=${MEDIUM_API_KEY:-}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  gcs_credentials: