name: Document Generation

on:
  workflow_dispatch:  # Manual trigger
    inputs:
      job_url:
        description: 'URL of the job posting to generate documents for'
        required: true
        type: string
      company:
        description: 'Company name'
        required: true
        type: string
      title:
        description: 'Job title'
        required: true
        type: string
      description:
        description: 'Job description'
        required: true
        type: string
  push:
    branches:
      - main
    paths:
      - 'scripts/generate_documents.py'
      - 'docs/**'

jobs:
  generate-documents:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Generate application documents
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.SLACK_CHANNEL_ID }}
          ENABLE_SLACK_NOTIFICATIONS: "true"
        run: |
          # Create temporary job info file
          echo '{
            "url": "${{ github.event.inputs.job_url }}",
            "company": "${{ github.event.inputs.company }}",
            "title": "${{ github.event.inputs.title }}",
            "description": "${{ github.event.inputs.description }}"
          }' > job_info.json
          
          # Generate documents
          python scripts/generate_documents.py job_info.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: Generate application documents'
          title: 'Generate Documents'
          body: |
            Generated new application documents for ${{ github.event.inputs.company }}:
            - Resume
            - Cover Letter
            
            Please review the changes and merge if they look good.
          branch: document-generation
          delete-branch: true
          base: main