name: Job Strategy Generator

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 9am UTC daily
  workflow_dispatch:  # Manual trigger
    inputs:
      job_limit:
        description: 'Number of job postings to return per search query'
        required: false
        default: '2'
        type: string

# Ensure only one workflow runs at a time
concurrency:
  group: job-strategy
  cancel-in-progress: true

jobs:
  generate-strategy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Generate job strategy
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.SLACK_CHANNEL_ID }}
          ENABLE_SLACK_NOTIFICATIONS: "true"
        run: |
          python scripts/job_strategy.py --job-limit ${{ github.event.inputs.job_limit || '2' }}
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: Update job search strategy'
          title: 'Update Job Search Strategy'
          body: |
            Automated job search strategy update
            
            - Generated at: $(date)
            - Jobs per search query: ${{ github.event.inputs.job_limit || '2' }}
            - Includes latest job opportunities and market insights
            - Using database from GCS bucket
            
            ## Generated Files
            - New strategy document in Markdown format
            - New strategy document in plain text format (for compatibility)
            
            ## Next Steps
            1. Review the strategy
            2. Consider any high-priority job opportunities
            3. Execute on daily tasks and goals
          branch: strategy-update
          delete-branch: true
          base: main