name: Job Strategy Generator

on:
  schedule:
    - cron: '0 16 * * *'  # Runs at 9:00 AM Pacific Time (16:00 UTC)
    - cron: '0 20 * * *'  # Runs at 1:00 PM Pacific Time (20:00 UTC)
  workflow_dispatch:  # Manual trigger
    inputs:
      job_limit:
        description: 'Number of job postings to return per search query'
        required: false
        default: '2'
        type: string

# Ensure only one workflow runs at a time
concurrency:
  group: job-strategy
  cancel-in-progress: true

jobs:
  generate-strategy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Generate job strategy
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.SLACK_CHANNEL_ID }}
          ENABLE_SLACK_NOTIFICATIONS: "true"
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python scripts/job_strategy.py --job-limit ${{ github.event.inputs.job_limit || '2' }}