name: Profile Data Management

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'inputs/Profile.pdf'
      - 'inputs/Resume.pdf'
      - 'inputs/CoverLetter.pdf'
      - 'inputs/profile.json'

# Sets permissions to allow PR creation
permissions:
  contents: write
  pull-requests: write

jobs:
  update-profile:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Process profile data
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
        run: |
          python scripts/init_db.py
          python scripts/profile_scraper.py
          python scripts/resume_parser.py
          python scripts/cover_letter_parser.py
          python scripts/combine_and_summarize.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: Update profile data'
          title: 'Update Profile Data'
          body: |
            Automated profile data update
            
            - Updated from latest profile documents
            - Includes LinkedIn profile, resume, and cover letter data
            - Using database from GCS bucket
          branch: profile-update
          delete-branch: true
          base: main